<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>fd5640a1-4226-4ace-83db-2a738b6f4133</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.text-white.underline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[4]/div/div/section/div/div/div[2]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Login&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a9a4233d-7b82-454a-8419-f965c39fda24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white underline</value>
      <webElementGuid>4b693446-e941-42b5-98c2-08f57ae6428d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>16fa6c5f-08d8-4096-9cc7-f8d204c1c993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/customer/login</value>
      <webElementGuid>6b38a049-f11e-4f96-bacd-e7c2a06cf1ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>18c53527-4f3d-43d4-b6ad-2fd1cfa2462e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-col&quot;]/div[@class=&quot;grow&quot;]/div[1]/section[@class=&quot;bg-linear-gradient&quot;]/div[@class=&quot;mx-auto max-w-7xl sm:px-4 py-16 pt-8&quot;]/div[@class=&quot;mx-auto flex flex-col items-center px-1 py-16 lg:flex-row-reverse lg:py-20&quot;]/div[@class=&quot;flex-1 text-center text-white lg:text-left&quot;]/div[@class=&quot;lg:pl-5&quot;]/div[@class=&quot;mt-8 flex flex-col items-center lg:flex-row&quot;]/a[@class=&quot;text-white underline&quot;]</value>
      <webElementGuid>1ff76cd5-6e09-4cf7-bf8d-54339e2f0cb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[4]/div/div/section/div/div/div[2]/div/div/a</value>
      <webElementGuid>ecadeb08-6b77-43a6-b3dc-2928aea4ffc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>3c4b6871-55ed-4312-acb7-80b5482d1da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register Employer'])[1]/following::a[1]</value>
      <webElementGuid>86d29764-1ff5-4147-b134-9796fa6efb91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hire the best IT Professionals in Vietnam with FITviec'])[1]/following::a[1]</value>
      <webElementGuid>5cc061a2-411e-4230-89ac-026511f77cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What makes FITviec different?'])[1]/preceding::a[1]</value>
      <webElementGuid>db41b70e-a5bf-46d8-9780-92f4ce140220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='High-value services for IT Employers'])[1]/preceding::a[1]</value>
      <webElementGuid>03341136-94cb-4d29-ae41-dd6be4a72571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>795cb0bd-4a32-419e-b4ff-958aa159891f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/customer/login')]</value>
      <webElementGuid>ff1acd17-39b3-41da-bee9-db24b35c0c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>0b12648a-b969-4b67-9e3d-58c07d031b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/customer/login' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>f705546b-6a76-47cd-8bac-2280e392cba7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
