<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apply</name>
   <tag></tag>
   <elementGuidId>ce8345dd-b4c2-4488-b373-31a1bf4b4f16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:r5:']/div[2]/div[5]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.px-4.py-2.bg-red-500.text-white.rounded-full</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Apply&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>844989ee-b945-4ff4-9eae-f183d74b4489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 py-2 bg-red-500 text-white rounded-full</value>
      <webElementGuid>b8c6ed0b-09ef-43f0-9e97-8595f527887c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>61537ef5-fa06-4a2c-82e6-c893db086a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r5:&quot;)/div[@class=&quot;p-4&quot;]/div[@class=&quot;flex justify-between&quot;]/button[@class=&quot;px-4 py-2 bg-red-500 text-white rounded-full&quot;]</value>
      <webElementGuid>08a3785a-5f4c-4951-9403-798d4ef2f506</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r5:']/div[2]/div[5]/button[2]</value>
      <webElementGuid>0922e24f-3272-4584-afab-d066600a1f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset filter'])[1]/following::button[1]</value>
      <webElementGuid>3f6711aa-af66-45dc-9bf1-f32285f23161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hybrid'])[1]/following::button[2]</value>
      <webElementGuid>4ca3aba2-efaa-4e4f-a2e4-2a8200e187ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::button[1]</value>
      <webElementGuid>5d882388-f2c1-47fb-b3ea-380a18655c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apply']/parent::*</value>
      <webElementGuid>a050ca0c-385b-4d2d-acf5-4b4d912f7f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button[2]</value>
      <webElementGuid>b7c6ec05-7708-4880-87ce-203f049ee473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Apply' or . = 'Apply')]</value>
      <webElementGuid>c0cc215c-6fc8-4077-8e1c-cdc0cb63de5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
