<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Senior</name>
   <tag></tag>
   <elementGuidId>ba865520-556a-4ef4-be42-1b378c9de075</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:r5:']/div[2]/div/div/button[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.px-3.py-1.rounded-full.border.bg-gray-200</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Senior&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bc6e2f6e-fa5a-4bf6-91dc-420baa8b3dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-3 py-1 rounded-full border bg-gray-200</value>
      <webElementGuid>c2ee2a8d-ee36-40fd-a5ac-1bca7ddf6d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Senior</value>
      <webElementGuid>cc6eac01-977b-4c54-b785-c72c3e02381c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r5:&quot;)/div[@class=&quot;p-4&quot;]/div[@class=&quot;mb-4&quot;]/div[@class=&quot;flex flex-wrap gap-2&quot;]/button[@class=&quot;px-3 py-1 rounded-full border bg-gray-200&quot;]</value>
      <webElementGuid>15ad982b-96d3-446e-a8e8-ecbd9c3970ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r5:']/div[2]/div/div/button[3]</value>
      <webElementGuid>c7ca0377-17d2-404b-a896-c3223c3d1772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Junior'])[1]/following::button[1]</value>
      <webElementGuid>058e4935-f6fe-4bba-a388-b63d7e41880a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fresher'])[1]/following::button[2]</value>
      <webElementGuid>2e356b70-d6d0-4935-a064-befbce9912c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manager'])[1]/preceding::button[1]</value>
      <webElementGuid>e01ec076-323c-4ce8-a282-6e9df4a5248a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salary'])[1]/preceding::button[2]</value>
      <webElementGuid>c08f3672-ace2-4cf0-8721-da06985429b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Senior']/parent::*</value>
      <webElementGuid>4be22f0f-2799-459a-98fc-da50931fde40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/button[3]</value>
      <webElementGuid>a6f8f9e6-df9f-479a-aaf0-fdf989bfed78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Senior' or . = 'Senior')]</value>
      <webElementGuid>8e63b8e3-8a70-4bfa-a5d0-8dfbc03aa4bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
