<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Send my CV</name>
   <tag></tag>
   <elementGuidId>18b93a4d-2298-40d9-a8de-949b40ca3e83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Send my CV&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>af699f49-bb6c-48b1-8ae7-c424387b77fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-[#ED1B2F] hover:bg-red-600 text-white w-full font-bold py-3 px-4 rounded focus:outline-none focus:shadow-outline</value>
      <webElementGuid>2d25b4d2-5309-41d4-bb07-0fbde1a10b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d6be9611-6799-4032-bace-989f9e21fbce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send my CV</value>
      <webElementGuid>9cd3985f-97b0-4bbd-8470-fff674952570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;p-[30px] pb-[150px] bg-gray-200 bg-opacity-50&quot;]/div[@class=&quot;max-w-[884px] ml-auto mr-auto relative&quot;]/div[@class=&quot;rounded-lg bg-white p-[32px] shadow-lg&quot;]/form[@class=&quot;bg-white  pt-6 pb-3 mb-4&quot;]/div[@class=&quot;flex items-center justify-center mt-6&quot;]/button[@class=&quot;bg-[#ED1B2F] hover:bg-red-600 text-white w-full font-bold py-3 px-4 rounded focus:outline-none focus:shadow-outline&quot;]</value>
      <webElementGuid>28bcb7b8-70e5-4ecf-a376-aad63455c94d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>67a949e1-b9a4-476b-99e7-6e8ae03ac1a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[4]/div[2]/div[2]/form/div[4]/button</value>
      <webElementGuid>aa41397d-d3f8-429c-991e-14f7dbbbf3c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What skills, work projects or achievements make you a strong candidate?'])[1]/following::button[1]</value>
      <webElementGuid>acd5b06e-78de-4c10-bdf0-7348d68fd679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Optional)'])[1]/following::button[1]</value>
      <webElementGuid>23b4b8bc-f289-4777-a05d-916bfc912bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ít nhưng mà chất'])[1]/preceding::button[1]</value>
      <webElementGuid>c4a22c02-f8a3-4a31-a829-89b843be4348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/preceding::button[4]</value>
      <webElementGuid>8b5f9ed1-242a-4197-8130-5c296ea3b4c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send my CV']/parent::*</value>
      <webElementGuid>f384c30b-acdb-42e7-bb7e-dbd2e87f5b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>6cb548ee-4945-4b75-bd8b-6afd6f781394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Send my CV' or . = 'Send my CV')]</value>
      <webElementGuid>384d085f-d8f4-4aa1-91a8-00a4b4cc0d85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
