<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Forgot password_form-input h-12 w-ful_5ed60f</name>
   <tag></tag>
   <elementGuidId>66246d2a-abee-427b-a4c7-07f7bfa5eee2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-input.h-12.w-full.rounded-sm.border.border-gray-300.px-4.py-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>522b1986-404e-4c90-97c8-11b5428b039e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>9ad3feb2-84e9-47ef-aba9-596bf21180d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input h-12 w-full rounded-sm border border-gray-300 px-4 py-2</value>
      <webElementGuid>cc08591a-bccb-47c9-be85-3f6d559028e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>aa82d463-3ac7-4cc8-984a-cdab625c4d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;mx-auto max-w-7xl sm:px-4 py-16 pt-8&quot;]/div[@class=&quot;flex gap-x-32&quot;]/div[@class=&quot;leftside w-5/12&quot;]/div[@class=&quot;mb-6&quot;]/div[@class=&quot;relative mb-1&quot;]/input[@class=&quot;form-input h-12 w-full rounded-sm border border-gray-300 px-4 py-2&quot;]</value>
      <webElementGuid>544eefbe-a90d-48e3-bcfc-b92c8e1e0bfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>c0cfbbd4-50c6-4e36-93f8-08a95fcf8165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[4]/div[2]/div/div[4]/div[2]/input</value>
      <webElementGuid>4afcaca9-2c0e-4483-9699-4d429d578951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>2ed3413b-e9cb-415a-9d3f-94c4912b3c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>eb465049-4be4-4be6-9a87-a059807c8737</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
