<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Viet_form-input h-12 w-full rounded-s_87e3dd_1</name>
   <tag></tag>
   <elementGuidId>66246d2a-abee-427b-a4c7-07f7bfa5eee2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-input.h-12.w-full.rounded-sm.border.text-slate-700.border-gray-300.px-4.py-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Confirm new password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1d96cfb-01b9-4e45-a6a0-710c17df413f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f2c45339-b38c-46f5-92f4-8f17a63642f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input h-12 w-full rounded-sm border text-slate-700 border-gray-300 px-4 py-2</value>
      <webElementGuid>437eff57-0e4f-487a-a960-2ee0c6ebbb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm new password</value>
      <webElementGuid>a72b08d6-8adb-4d5b-b928-d2af457b5962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen bg-gray-200&quot;]/div[@class=&quot;mx-auto max-w-7xl sm:px-4 max-w-[1000px] pb-4 pt-4&quot;]/div[@class=&quot;mt-4 flex w-full flex-col rounded-lg bg-white shadow-lg&quot;]/div[@class=&quot;mx-8 grid grid-cols-12   pb-4 pt-6&quot;]/div[@class=&quot;col-span-9 flex flex-col justify-center&quot;]/div[@class=&quot;mb-2&quot;]/div[@class=&quot;relative mb-1&quot;]/input[@class=&quot;form-input h-12 w-full rounded-sm border text-slate-700 border-gray-300 px-4 py-2&quot;]</value>
      <webElementGuid>b207a505-867b-48eb-9ba5-236b33abcbf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>0388d8d9-76ad-440a-b294-fd4d0ba291f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[4]/div/div/div[3]/div[2]/div[3]/div/input</value>
      <webElementGuid>49d8d98f-ea3e-49c2-867e-d700ea0c2014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>8503c540-43be-4285-9718-687c6954667c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Confirm new password']</value>
      <webElementGuid>4eedaf07-8840-4cbe-bd9d-e89c492f7885</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
