<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Month123456789101112</name>
   <tag></tag>
   <elementGuidId>fa532e4d-a221-4f1a-bd42-7fe44983f6d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='fromMonth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;fromMonth&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;fromMonth&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4d842c33-2d1d-48f2-849f-3c07cfeaca56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fromMonth</value>
      <webElementGuid>8f9d374c-18fa-420f-9b3d-922de6649e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 w-full rounded border p-2 border-gray-300</value>
      <webElementGuid>19552038-e5a4-4a20-8824-34ebfd5bdb6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Month123456789101112</value>
      <webElementGuid>aed76acf-4db0-410d-9d58-bb600fa64a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;work-experience-popup&quot;)/div[@class=&quot;mt-10 flex h-[75%] max-h-[90vh] w-[50%] flex-col justify-between overflow-auto  rounded-lg bg-white p-8 shadow-md transition-all duration-300 ease-in-out&quot;]/form[1]/div[@class=&quot;mb-4 flex&quot;]/div[@class=&quot;mr-4&quot;]/select[@class=&quot;mt-1 w-full rounded border p-2 border-gray-300&quot;]</value>
      <webElementGuid>98b6e3b4-361a-4d4a-9ac5-3cd929b081d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='fromMonth']</value>
      <webElementGuid>e68bdc6c-75b6-495d-93b6-1015f3ceabd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='work-experience-popup']/div/form/div[4]/div/select</value>
      <webElementGuid>183f1134-09f0-47b3-a105-193dd5e0c025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From'])[1]/following::select[1]</value>
      <webElementGuid>96adf228-bf3a-4caf-8e64-35231671dac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I am currently working here'])[1]/following::select[1]</value>
      <webElementGuid>500d0d20-c158-4956-9f6e-eaa9687a51da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year'])[1]/preceding::select[1]</value>
      <webElementGuid>5279e4cb-eefd-456c-8fa5-032f6dc5be53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::select[2]</value>
      <webElementGuid>aeb008af-685a-4b55-b698-8f0d5294f792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>b486b799-32d5-43ea-b5d1-3ae2ef6b2568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fromMonth' and (text() = 'Month123456789101112' or . = 'Month123456789101112')]</value>
      <webElementGuid>4eab0ed4-e2df-499c-b751-46d55e576f15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
