<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sign In with Google</name>
   <tag></tag>
   <elementGuidId>a0c01b5c-74e8-4370-bd43-ade390d42eff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.pl-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[4]/div[2]/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Google Logo Sign In with Google&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7045791f-14f4-453f-9ac7-b652e1c14c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pl-2</value>
      <webElementGuid>03a9ef36-92f3-49fc-b986-63bf134c82d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In with Google</value>
      <webElementGuid>8b4e992c-53e5-47ef-a8c1-ef38dec1241e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;mx-auto max-w-7xl sm:px-4 py-16 pt-8&quot;]/div[@class=&quot;flex gap-x-32&quot;]/div[@class=&quot;leftside w-5/12&quot;]/button[@class=&quot;flex h-12 w-full items-center justify-center gap-0 rounded-sm border border-red-500 py-2 font-bold text-red-500 hover:bg-red-50&quot;]/span[@class=&quot;pl-2&quot;]</value>
      <webElementGuid>b3edd2ac-caa6-45d1-8992-0a365ca66748</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[4]/div[2]/div/button/span</value>
      <webElementGuid>500f5801-82ee-43f0-9548-0d76ae5adbd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to'])[1]/following::span[1]</value>
      <webElementGuid>67873faa-9896-47d8-9593-637e341c4238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='or'])[1]/preceding::span[1]</value>
      <webElementGuid>c83258bb-226f-4865-aad7-7e8a2abf5a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::span[1]</value>
      <webElementGuid>96ef62a2-10fd-419d-b123-69aecdb3e8ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign In with Google']/parent::*</value>
      <webElementGuid>5fd540dc-e67c-4c41-897d-3fbcf23638dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/span</value>
      <webElementGuid>8a2f8968-8334-4231-8012-3577dca872ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Sign In with Google' or . = 'Sign In with Google')]</value>
      <webElementGuid>e895d9f7-ecf9-4eb0-bfb4-3e2935a0661a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
